StartupEvents.registry('item', e =>{
    e.create('alien:nosee')  
    .displayName('§4不可视§k&%&$§4之物0')
    .texture('a_blue_alien:item/nosee')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`§4不可视§k&%&$§4之物0自传说中来，掌握最高价的科技，是所有外星人的至尊王者和唯一统治者`)

    e.create('alien:alien0')
    .displayName('alien0')
    .texture('a_blue_alien:item/alien0')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`最常见的黑色外星人`)

    e.create('alien:alien1')
    .displayName('alien1')
    .texture('a_blue_alien:item/alien1')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`浅蓝色外星人`)

    e.create('alien:alien2')
    .displayName('alien2')
    .texture('a_blue_alien:item/alien2')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`银色外星人`)

    e.create('alien:alien3')
    .displayName('alien3')
    .texture('a_blue_alien:item/alien3')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`深蓝色外星人`)

    e.create('alien:alien4')
    .displayName('alien4')
    .texture('a_blue_alien:item/alien4')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`墨色外星人`)

    e.create('alien:alien5')
    .displayName('alien5')
    .texture('a_blue_alien:item/alien5')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`绿色外星人`)

    e.create('alien:alien6')
    .displayName('alien6')
    .texture('a_blue_alien:item/alien6')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`金色外星人`)

    e.create('alien:alien7')
    .displayName('alien7')
    .texture('a_blue_alien:item/alien7')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`红色外星人`)

    e.create('alien:alien8')
    .displayName('alien8')
    .texture('a_blue_alien:item/alien8')
    .maxStackSize(1)
    .fireResistant(false)
    .rarity('epic')
    .tooltip(`紫色外星人`)

    e.create('alien:upgrade1')
    .displayName('I阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`I阶升级凭证`)

    e.create('alien:upgrade2')
    .displayName('II阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`II阶升级凭证`)

    e.create('alien:upgrade3')
    .displayName('III阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`III阶升级凭证`)

    e.create('alien:upgrade4')
    .displayName('IV阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`IV阶升级凭证`)

    e.create('alien:upgrade5')
    .displayName('V阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`V阶升级凭证`)

    e.create('alien:upgrade6')
    .displayName('VI阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`VI阶升级凭证`)

    e.create('alien:upgrade7')
    .displayName('VII阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`VII阶升级凭证`)

    e.create('alien:upgrade8')
    .displayName('VIII阶升级凭证')
    .texture('a_blue_alien:item/upgrade')
    .tooltip(`VIII阶升级凭证`)

    e.create('alien:heroine')
    .displayName('山海§e[a yellow alien]')
    .texture('a_blue_alien:item/heroine')
    .tooltip(`山海§e[a yellow alien]`)
})
